using System; using System.IO; using System.Linq; using UnityEngine; using UnityEditor; using UnityEditor.SceneManagement;
namespace Simus.Editor {
 public static class StageBuilder {
 public const string Scene="Assets/Scenes/NeighborhoodLive.unity";
 public static void Inspect(){EditorSceneManager.OpenScene("Assets/Scenes/Neighborhood.unity"); var rows=UnityEngine.Object.FindObjectsByType<Renderer>(FindObjectsSortMode.None).Where(r=>r.sharedMaterials.Any(m=>m!=null&&(m.name.ToLower().Contains("walk")||m.name.ToLower().Contains("road")))).Select(r=>r.name+" "+r.bounds.ToString()); File.WriteAllLines("../Verification/paths.txt",rows);}
 public static void Build(){EditorSceneManager.OpenScene("Assets/Scenes/Neighborhood.unity");var root=new GameObject("SIMUS Live — public API only");var client=root.AddComponent<CityLiveClient>();client.explicitMockMode=false;var life=root.AddComponent<CityLife>();life.client=client;life.path=new[]{new Vector3(-64,1.4f,12),new Vector3(-64,1.4f,45)};life.previewNpcs=new Transform[3];for(int i=0;i<3;i++){var npc=GameObject.CreatePrimitive(PrimitiveType.Capsule);npc.name="PREVIEW NPC "+i+" — not a participant";npc.transform.SetParent(root.transform);npc.transform.position=life.PositionAt(i*7);life.previewNpcs[i]=npc.transform;}
 life.moodBeacon=Beacon(root,"Happiness temporary indicator",-66);life.cleanlinessBeacon=Beacon(root,"Cleanliness temporary indicator",-62);life.safetyBeacon=Beacon(root,"Safety temporary indicator",-58);
 var walk=UnityEngine.Object.FindObjectsByType<MeshRenderer>(FindObjectsSortMode.None).Single(r=>r.name=="Restaurant pedestrian lane");var collider=walk.gameObject.AddComponent<MeshCollider>();Physics.SyncTransforms();for(int i=0;i<=33;i++){var origin=new Vector3(-64,10,12+i);if(!collider.Raycast(new Ray(origin,Vector3.down),out var hit,20))throw new Exception("Path off actual walkway "+origin);}UnityEngine.Object.DestroyImmediate(collider);File.WriteAllText("../Verification/path-validation.txt","PASS 34 samples raycast actual Restaurant pedestrian lane mesh. X=-64, Z=12..45, ground Y=0.4. Capsule center Y=1.4. Speed=2 m/s; 33 sec loop. PREVIEW only.\n");EditorSceneManager.SaveScene(UnityEngine.SceneManagement.SceneManager.GetActiveScene(),Scene);AssetDatabase.SaveAssets();Debug.Log("SIMUS_LIVE_SCENE_BUILT");}
 static Renderer Beacon(GameObject root,string name,float x){var g=GameObject.CreatePrimitive(PrimitiveType.Cube);g.name=name;g.transform.SetParent(root.transform);g.transform.position=new Vector3(x,2,48);g.transform.localScale=new Vector3(2,4,2);return g.GetComponent<Renderer>();}
 public static void Verify(){Build();SessionState.SetInt("STAGE_FRAME",0);EditorApplication.EnterPlaymode();}
 }
 [InitializeOnLoad] public static class StagePlayVerification {
 static StagePlayVerification(){if(Application.isBatchMode&&Environment.GetCommandLineArgs().Contains("-simusStageTest"))EditorApplication.update+=Tick;}
 static CityLiveClient test; static CityLife life; static float previous;
 static string State(string id,long v,string status="RUNNING",string start="2026-09-24T00:00:00Z")=>"{\"round\":{\"id\":\""+id+"\",\"started\":\""+start+"\",\"status\":\""+status+"\",\"version\":"+v+",\"happiness\":50,\"safety\":50,\"cleanliness\":50,\"pollution\":0},\"server_time\":\"2026-09-24T01:00:00Z\"}";
 static void Assert(bool value,string text){if(!value)throw new Exception(text);}
 static void Tick(){if(!EditorApplication.isPlaying)return;int frame=SessionState.GetInt("STAGE_FRAME",0)+1;SessionState.SetInt("STAGE_FRAME",frame);try{if(frame==10){test=UnityEngine.Object.FindFirstObjectByType<CityLiveClient>();test.StopAllCoroutines();life=test.GetComponent<CityLife>();Assert(test.AcceptJson(State("A",2)),"initial");Assert(!test.AcceptJson(State("A",1)),"old version");Assert(test.AcceptJson(State("B",0,"RUNNING","2026-09-24T00:10:00Z")),"new round");Assert(!test.AcceptJson(State("A",9)),"retired round");previous=life.Elapsed;}if(frame==100){Assert(life.Elapsed>previous,"NPC did not move");Assert(test.AcceptJson(State("B",1,"FINALIZED","2026-09-24T00:10:00Z")),"finalize");previous=life.Elapsed;}if(frame==150){Assert(life.Elapsed==previous,"NPC moved after final");test.AcceptJson(State("B",99,"RUNNING","2026-09-24T00:10:00Z"));Assert(test.Current.status=="FINALIZED"&&test.Current.version==1,"Final state mutated");File.WriteAllText("../Verification/stage-play.txt","PASS Unity "+Application.unityVersion+" actual Play mode 150 editor updates. Mock injected: initial, stale version, new round, retired round rejection, NPC movement, final freeze + immutable final. HTTP integration not asserted by this test.\n");Debug.Log("SIMUS_STAGE_PLAY_PASS");EditorApplication.Exit(0);}}catch(Exception e){Debug.LogException(e);EditorApplication.Exit(1);}}
 }
}
