// Generate a reviewable PostgreSQL seed from the approved Markdown source.
import { readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const directory = path.dirname(fileURLToPath(import.meta.url));
const source = path.resolve(directory, '../docs/content/situations-and-choices.md');
const output = path.join(directory, 'seed_exhibition.sql');
const lines = (await readFile(source, 'utf8')).split(/\r?\n/);
const situations = [];
let current;
const fields = { '행복': 'happiness', '치안': 'safety', '청결': 'cleanliness', '오염': 'pollution', '질서': 'order', '선': 'morality' };
for (const line of lines) {
  const heading = line.match(/^### (\d+)\. (.+)$/);
  if (heading) {
    const number = Number(heading[1]);
    if (number !== situations.length + 1) throw new Error(`Unexpected situation number: ${number}`);
    current = { number, title: heading[2], choices: [] };
    situations.push(current);
    continue;
  }
  const choice = line.match(/^- (.+?) → `(.+)`$/);
  if (!choice) continue;
  if (!current) throw new Error('Choice without situation');
  const scores = Object.fromEntries(Object.values(fields).map(field => [field, 0]));
  if (choice[2] !== '변화 없음') {
    for (const part of choice[2].split(' / ')) {
      const match = part.match(/^(.+) ([+-]\d+)$/);
      if (!match || !Object.hasOwn(fields, match[1])) throw new Error(`Unknown score: ${part}`);
      scores[fields[match[1]]] = Number(match[2]);
    }
  }
  const label = choice[1].replace(/^\*\*/, '').replace(/\*\*$/, '');
  current.choices.push({ number: current.choices.length + 1, label, scores });
}
if (situations.length !== 30 || situations.reduce((sum, item) => sum + item.choices.length, 0) !== 91 ||
  situations.some(item => item.choices.length < 2)) throw new Error('Expected exactly 30 situations and 91 choices');
const all = situations.flatMap(item => item.choices);
for (const item of all) {
  const s = item.scores;
  if ([s.order, s.morality].some(value => value < -4 || value > 3)) throw new Error('Alignment outside migration range');
}
const q = value => `'${String(value).replaceAll("'", "''")}'`;
const uuid = (group, number) => q(`${group}0000000-0000-0000-0000-${String(number).padStart(12, '0')}`);
const sid = q('16000000-0000-0000-0000-000000000001');
const region = q('26000000-0000-0000-0000-000000000001');
const situationId = n => uuid(3, n);
const choiceId = (n, c) => uuid(4, n * 10 + c);
const situationRows = situations.map(item => `  (${sid},${situationId(item.number)},${q(`EXHIBITION_${String(item.number).padStart(2, '0')}`)},${q(item.title)},${q(item.title)},${item.number})`).join(',\n');
const choiceRows = situations.flatMap(item => item.choices.map(choice => {
  const s = choice.scores;
  const importance = Math.max(Math.abs(s.order), Math.abs(s.morality)) > 1 ? 'MAJOR' : 'NORMAL';
  return `  (${sid},${situationId(item.number)},${choiceId(item.number, choice.number)},${q(choice.label)},${choice.number},${q(importance)},${s.order},${s.morality},${s.happiness},${s.safety},${s.cleanliness})`;
})).join(',\n');
const effectRows = situations.flatMap(item => item.choices.map(choice =>
  `  (${sid},${situationId(item.number)},${choiceId(item.number, choice.number)},${region},${choice.scores.pollution})`)).join(',\n');
const sql = `-- GENERATED by db/generate_exhibition_seed.mjs from docs/content/situations-and-choices.md.
-- Development DRAFT template only. Requires 001..006 and seed_demo.sql; never apply to an operational DB.
-- One city-wide region is provisional until the 3B map provides placement coordinates.
BEGIN;
SET LOCAL search_path = simus, public;
INSERT INTO simulation_sessions(id,name,status,scheduled_end_at,admission_buffer,
  expected_participants,expected_answers_per_person,impact_scale,rules_snapshot,created_by_admin_id)
SELECT ${sid},'전시 30상황 콘텐츠 초안','DRAFT',clock_timestamp()+interval '7 days',admission_buffer,
  500,30,impact_scale,jsonb_set(rules_snapshot,'{initial_region_pollution}','{"EXHIBITION_CITY":0}'::jsonb),created_by_admin_id
FROM simulation_sessions WHERE id='10000000-0000-0000-0000-000000000001' AND status='DRAFT';
INSERT INTO session_regions(session_id,id,code,name,aggregation_weight,map_metadata)
VALUES (${sid},${region},'EXHIBITION_CITY','전시 도시 전체',1,'{"placement":"pending-map-v1"}'::jsonb);
INSERT INTO session_situations(session_id,id,code,title,body,display_order) VALUES
${situationRows};
INSERT INTO session_choices(session_id,situation_id,id,label,display_order,importance,
  alignment_dx,alignment_dy,happiness_base,safety_base,cleanliness_base) VALUES
${choiceRows};
INSERT INTO choice_region_effects(session_id,situation_id,choice_id,region_id,pollution_base) VALUES
${effectRows};
COMMIT;
`;
if (process.argv.includes('--check')) {
  if ((await readFile(output, 'utf8')) !== sql) throw new Error('seed_exhibition.sql is stale');
} else {
  await writeFile(output, sql);
}
console.log(`PASS: ${situations.length} situations, ${all.length} choices, score range ${Math.min(...all.flatMap(c => [c.scores.order, c.scores.morality]))}..${Math.max(...all.flatMap(c => [c.scores.order, c.scores.morality]))}`);
