import {api,ApiError,pendingKey,readPending,makeChoice,isFinal,canChoose,visibleResult} from './api.js';
const app=document.querySelector('#app'),connection=document.querySelector('#connection');
let authMissingRound=null;let round=null,me=null,online=false,busy=false,polling=false,modeReady=false,message='',pending=readPending(),historyRound=new URLSearchParams(location.search).get('round');
const selected=new Map();
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const date=x=>x?new Date(x).toLocaleString('ko-KR'):'';
function notice(text){message=text;render();}
function render(){
 connection.className=online?'':'error';connection.textContent=online?'': '서버 연결을 확인하고 있어요. 마지막으로 확인한 상태이며 신규 제출은 잠시 멈춥니다.';
 if(!round){app.innerHTML=`<section class="card"><h2>회차를 기다리고 있어요</h2><p>${esc(message||'운영자가 회차를 시작하면 참여할 수 있어요.')}</p><button id="refresh">다시 확인</button></section>`;document.querySelector('#refresh').onclick=()=>refresh();return;}
 const final=isFinal(round),result=visibleResult(round,me),answers=me?.answers||[];
 app.innerHTML=`<section class="card"><span class="pill">${historyRound?'과거 회차': '현재 회차'} · ${final?'결과 공개':round.accepting?'선택 접수 중':'입력 마감 · 종료 준비 중'}</span><h2>${esc(round.name)}</h2><p class="muted">회차 ${esc(round.id)}<br>도시 버전 ${esc(round.version)} · 서버 확인 ${esc(date(round.server_time))}</p><div class="stats">${[['행복도','happiness'],['치안','safety'],['청결도','cleanliness'],['오염도','pollution']].map(([label,key])=>`<div class="stat">${label}<strong>${Number(round[key]).toFixed(1)}${key==='pollution'?'%':''}</strong></div>`).join('')}</div><p class="muted time">입력 마감 ${esc(date(round.cutoff))}<br>예정 종료 ${esc(date(round.ends))}</p>${!round.accepting&&!final?'<p class="notice">종료 준비 중으로 새로운 선택이 반영되지 않아요. 서버가 최종 결과를 확정하면 공개됩니다.</p>':''}</section>
 ${message?`<p class="notice" role="status">${esc(message)}</p>`:''}
 ${pending?`<section class="card"><h3>제출 상태 확인 필요</h3><p>응답을 확인하지 못한 요청이 있어요. 새 선택을 보내기 전에 같은 요청 번호와 내용으로 확인합니다.</p><p class="muted">대상 회차 ${esc(pending.round)}</p><button id="retry" ${busy||!online?'disabled':''}>${busy?'처리 중…':'동일 요청 다시 확인'}</button></section>`:''}
 ${!me?.joined?`<section class="card"><h2>${historyRound?'이 회차의 본인 참여 기록이 없어요':'도시의 하루에 참여하세요'}</h2><p>같은 브라우저에서는 기존 참여 정보를 복원합니다.</p>${!historyRound?`<button id="join" class="primary" ${!canChoose(round,online,busy)||!modeReady?'disabled':''}>참여 시작</button>`:''}</section>`:final?`<section class="card"><h2>나의 최종 결과</h2>${result?`<h3>${esc(result.alignment)}</h3><p>${esc(result.interpretation)}</p><p>질서–혼돈 ${esc(result.x)} · 선–악 ${esc(result.y)}</p><p>${Number(result.count)===0?'참여한 선택 없음':`${esc(result.count)}개의 선택에 참여했어요.`}</p><p class="muted">전시 속 행동의 경향이며 실제 인격 평가나 순위가 아닙니다.</p>`:'<p>개인 결과를 아직 확인하지 못했어요. 다시 연결해 확인합니다.</p>'}</section>`:`<section class="card"><h2>일상 속 나의 선택</h2><p>${esc(me.count)}개 상황 응답 완료 · 개인 성향은 종료 후 공개됩니다.</p></section>${(me.situations||[]).map(s=>{const answer=answers.find(a=>a.situation_id===s.id);return `<section class="card"><h3>${esc(s.title)}</h3><p>${esc(s.body)}</p>${answer?`<p class="notice">이미 응답한 상황 · ${esc(s.choices.find(c=>c.id===answer.choice_id)?.label||'선택 저장 완료')}</p>`:`<fieldset class="choices" ${!canChoose(round,online,busy)||pending?'disabled':''}><legend class="muted">행동 하나를 선택하세요</legend>${s.choices.map(c=>`<label class="option"><input type="radio" name="${esc(s.id)}" value="${esc(c.id)}" ${selected.get(s.id)===c.id?'checked':''}><span>${esc(c.label)}</span></label>`).join('')}</fieldset><p class="muted">제출한 선택은 취소하거나 변경할 수 없어요.</p><button class="primary submit" data-situation="${esc(s.id)}" ${!canChoose(round,online,busy)||pending||!selected.has(s.id)?'disabled':''}>${busy?'처리 중…':'이 행동 제출하기'}</button>`}</section>`;}).join('')}`}
 <section class="card"><h3>본인 NPC · 학과 · 알림</h3><p class="muted">본인 NPC 추적과 최종 캐릭터는 공유 식별·위치 연결을 준비 중입니다. 학과 선택은 공식 목록과 서버 저장 기능이 준비된 뒤 제공됩니다. 이 화면이 열려 있으면 결과 공개를 자동 확인하며, 외부 알림은 신청·발송하지 않습니다.</p></section>
 <section class="card"><h3>지난 회차 결과</h3><div class="history">${(me?.history||[]).map(h=>`<a href="?round=${encodeURIComponent(h.id)}">${esc(h.name)} 결과 보기</a>`).join('')||'<p class="muted">이 브라우저에서 확인할 과거 결과가 없어요.</p>'}</div>${historyRound?'<p><a href="./">현재 회차로 돌아가기</a></p>':''}</section>`;
 document.querySelector('#join')?.addEventListener('click',join);
 document.querySelector('#retry')?.addEventListener('click',()=>submit(pending));
 document.querySelectorAll('input[type=radio]').forEach(input=>input.onchange=()=>{selected.set(input.name,input.value);render();});
 document.querySelectorAll('.submit').forEach(button=>button.onclick=()=>{const sid=button.dataset.situation;const body=makeChoice(round.id,sid,selected.get(sid));try{localStorage.setItem(pendingKey,JSON.stringify(body));pending=body;}catch{notice('브라우저 저장소를 사용할 수 없어 안전한 재시도를 준비하지 못했어요. 저장소 설정을 확인해 주세요.');return;}submit(body);});
}
async function refresh(){if(polling||busy)return;polling=true;try{const state=await api('/api/state'+(historyRound?'?round='+encodeURIComponent(historyRound):''));const next=state.round;if(round&&next.id===round.id&&next.version<round.version)return;const previous=round;round={...next,server_time:state.server_time};if(authMissingRound!==round.id){try{me=await api('/api/me?round='+encodeURIComponent(round.id));authMissingRound=null;}catch(error){if(error.status===401){me=null;authMissingRound=round.id;}else throw error;}}else me=null;online=true;if(previous&&previous.id!==round.id){selected.clear();message='새 회차가 시작되었어요. 참여 시작을 눌러주세요.';}if(previous&&!isFinal(previous)&&isFinal(round))message='결과가 공개되었어요. 아래에서 본인 결과를 확인하세요.';if(pending&&pending.round===round.id&&me?.answers?.some(a=>a.situation_id===pending.situation)){localStorage.removeItem(pendingKey);pending=null;message='서버에 저장된 응답을 복원했어요. 이미 응답한 선택은 변경할 수 없습니다.';}}catch(error){online=false;message=error.message;}finally{polling=false;render();}}
async function join(){busy=true;render();try{await api('/api/join',{round:round.id});authMissingRound=null;message='참여 정보가 연결되었어요.';}catch(error){message=error.message;}finally{busy=false;await refresh();}}
async function submit(body){if(!body||busy)return;busy=true;notice('선택을 처리하고 있어요.');try{const result=await api('/api/choice',body);localStorage.removeItem(pendingKey);pending=null;message=result.replayed?'이미 저장된 요청을 확인했어요. 중복 반영되지 않았습니다.':'선택이 저장되었어요. 감사합니다.';}catch(error){message=error.message;if(error.status>=400&&error.status<500&&error.status!==408&&error.status!==429){localStorage.removeItem(pendingKey);pending=null;}if(error.status===0||error.status>=500)online=false;}finally{busy=false;await refresh();}}
async function init(){try{const config=await api('/client-config.json');if(!['live','mock'].includes(config.mode))throw new Error('연결 모드를 확인할 수 없어요.');modeReady=true;const el=document.querySelector('#mode');el.className='banner '+(config.mode==='mock'?'mock':'');el.textContent=(config.mode==='mock'?'모의 데이터 · 실제 서버 기록이 아닙니다':'실제 서버 연결 모드')+(config.label?' · '+config.label:'');}catch{document.querySelector('#mode').textContent='연결 환경 확인 실패 · 참여 시작 중지';}await refresh();}
window.addEventListener('online',refresh);document.addEventListener('visibilitychange',()=>{if(!document.hidden)refresh();});setInterval(()=>{if(!document.hidden)refresh();},1000);init();
